# Generated by Django 2.2.7 on 2019-11-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da série')),
                ('nota', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Nota')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='image_series/', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Série',
                'verbose_name_plural': 'Séries',
                'ordering': ['nome'],
            },
        ),
    ]
